image: alpine:latest

variables:
  VERSION: 1.0.0

stages:
  - lint
  - test
  - create_tag

shellcheck:
  stage: lint
  before_script:
    - apk add shellcheck
    - shellcheck --version
  script:
    - shellcheck ./src/run.sh
  except:
    - /^\d+\.\d+\.\d+$/

pylint:
  stage: lint
  script:
    - apk add --update --no-cache python3-dev gcc libc-dev libffi-dev
    - ln -sf python3 /usr/bin/python
    - ln -sf pip3 /usr/bin/pip
    - python -m ensurepip
    - python -m pip install --no-cache --upgrade pip setuptools requests pylint
    - python -m pylint --version
    - PYTHONPATH=${PYTHONPATH}:$(dirname %d) python -m pylint ./src
  except:
    - /^\d+\.\d+\.\d+$/

gitlab_release:
  when: manual
  stage: create_tag
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Releasing latest tag..."
  release:
    tag_name: $VERSION
    description: ./CHANGELOG.md
  only:
    - master
